services:
  mysql:
    image: mysql:8.4
    container_name: shared-mysql
    restart: unless-stopped

    env_file:
      - .env

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - shared-network

  redis:
    image: redis:7-alpine
    container_name: shared-redis
    restart: unless-stopped

    command: redis-server --appendonly yes

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    networks:
      - shared-network

volumes:
  mysql_data:
  redis_data:

networks:
  shared-network:
    name: shared-network

